/* tslint:disable */
/* eslint-disable */
/**
 * Cards API
 * The api to manage cards
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateCardDto
 */
export interface CreateCardDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    'spaceID': string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardDto
     */
    'parentCardID': string;
    /**
     * 
     * @type {object}
     * @memberof CreateCardDto
     */
    'attributes': object;
}
/**
 * 
 * @export
 * @interface CreateSpaceDto
 */
export interface CreateSpaceDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSpaceDto
     */
    'spaceID': string;
}
/**
 * 
 * @export
 * @interface SignInRequest
 */
export interface SignInRequest {
    /**
     * 
     * @type {string}
     * @memberof SignInRequest
     */
    'login': string;
    /**
     * 
     * @type {string}
     * @memberof SignInRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UpdateCardAttributesDto
 */
export interface UpdateCardAttributesDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCardAttributesDto
     */
    'spaceID': string;
    /**
     * 
     * @type {object}
     * @memberof UpdateCardAttributesDto
     */
    'attributes': object;
}
/**
 * 
 * @export
 * @interface UpdateCardDto
 */
export interface UpdateCardDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    'spaceID': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardDto
     */
    'parentCardID': string;
    /**
     * 
     * @type {object}
     * @memberof UpdateCardDto
     */
    'attributes': object;
}
/**
 * 
 * @export
 * @interface UpdateSpaceDto
 */
export interface UpdateSpaceDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateSpaceDto
     */
    'spaceID'?: string;
}

/**
 * CardsAuthApi - axios parameter creator
 * @export
 */
export const CardsAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerCheckIdentity: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/whoami`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SignInRequest} signInRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerSignIn: async (signInRequest: SignInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInRequest' is not null or undefined
            assertParamExists('authControllerSignIn', 'signInRequest', signInRequest)
            const localVarPath = `/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CardsAuthApi - functional programming interface
 * @export
 */
export const CardsAuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CardsAuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerCheckIdentity(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerCheckIdentity(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsAuthApi.authControllerCheckIdentity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SignInRequest} signInRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerSignIn(signInRequest: SignInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerSignIn(signInRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsAuthApi.authControllerSignIn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CardsAuthApi - factory interface
 * @export
 */
export const CardsAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CardsAuthApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerCheckIdentity(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authControllerCheckIdentity(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsAuthApiAuthControllerSignInRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerSignIn(requestParameters: CardsAuthApiAuthControllerSignInRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authControllerSignIn(requestParameters.signInRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for authControllerSignIn operation in CardsAuthApi.
 * @export
 * @interface CardsAuthApiAuthControllerSignInRequest
 */
export interface CardsAuthApiAuthControllerSignInRequest {
    /**
     * 
     * @type {SignInRequest}
     * @memberof CardsAuthApiAuthControllerSignIn
     */
    readonly signInRequest: SignInRequest
}

/**
 * CardsAuthApi - object-oriented interface
 * @export
 * @class CardsAuthApi
 * @extends {BaseAPI}
 */
export class CardsAuthApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsAuthApi
     */
    public authControllerCheckIdentity(options?: RawAxiosRequestConfig) {
        return CardsAuthApiFp(this.configuration).authControllerCheckIdentity(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsAuthApiAuthControllerSignInRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsAuthApi
     */
    public authControllerSignIn(requestParameters: CardsAuthApiAuthControllerSignInRequest, options?: RawAxiosRequestConfig) {
        return CardsAuthApiFp(this.configuration).authControllerSignIn(requestParameters.signInRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CardsCRUDApi - axios parameter creator
 * @export
 */
export const CardsCRUDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} type 
         * @param {CreateCardDto} createCardDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerCreate: async (type: string, createCardDto: CreateCardDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerCreate', 'type', type)
            // verify required parameter 'createCardDto' is not null or undefined
            assertParamExists('cardControllerCreate', 'createCardDto', createCardDto)
            const localVarPath = `/card/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCardDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerFindAllInSpace: async (spaceID: string, type: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spaceID' is not null or undefined
            assertParamExists('cardControllerFindAllInSpace', 'spaceID', spaceID)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerFindAllInSpace', 'type', type)
            const localVarPath = `/card/list/{spaceID}/{type}`
                .replace(`{${"spaceID"}}`, encodeURIComponent(String(spaceID)))
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {string} parentID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerFindChildren: async (spaceID: string, type: string, parentID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spaceID' is not null or undefined
            assertParamExists('cardControllerFindChildren', 'spaceID', spaceID)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerFindChildren', 'type', type)
            // verify required parameter 'parentID' is not null or undefined
            assertParamExists('cardControllerFindChildren', 'parentID', parentID)
            const localVarPath = `/card/list/{spaceID}/{type}/children-of/{parentID}`
                .replace(`{${"spaceID"}}`, encodeURIComponent(String(spaceID)))
                .replace(`{${"type"}}`, encodeURIComponent(String(type)))
                .replace(`{${"parentID"}}`, encodeURIComponent(String(parentID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerFindOne: async (spaceID: string, type: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spaceID' is not null or undefined
            assertParamExists('cardControllerFindOne', 'spaceID', spaceID)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerFindOne', 'type', type)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cardControllerFindOne', 'id', id)
            const localVarPath = `/card/{spaceID}/{type}/{id}`
                .replace(`{${"spaceID"}}`, encodeURIComponent(String(spaceID)))
                .replace(`{${"type"}}`, encodeURIComponent(String(type)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerRemove: async (spaceID: string, type: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spaceID' is not null or undefined
            assertParamExists('cardControllerRemove', 'spaceID', spaceID)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerRemove', 'type', type)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cardControllerRemove', 'id', id)
            const localVarPath = `/card/{spaceID}/{type}/{id}`
                .replace(`{${"spaceID"}}`, encodeURIComponent(String(spaceID)))
                .replace(`{${"type"}}`, encodeURIComponent(String(type)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} type 
         * @param {string} id 
         * @param {UpdateCardDto} updateCardDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerUpdate: async (type: string, id: string, updateCardDto: UpdateCardDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerUpdate', 'type', type)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cardControllerUpdate', 'id', id)
            // verify required parameter 'updateCardDto' is not null or undefined
            assertParamExists('cardControllerUpdate', 'updateCardDto', updateCardDto)
            const localVarPath = `/card/{type}/{id}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCardDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} type 
         * @param {string} id 
         * @param {UpdateCardAttributesDto} updateCardAttributesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerUpdateCardAttributes: async (type: string, id: string, updateCardAttributesDto: UpdateCardAttributesDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('cardControllerUpdateCardAttributes', 'type', type)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cardControllerUpdateCardAttributes', 'id', id)
            // verify required parameter 'updateCardAttributesDto' is not null or undefined
            assertParamExists('cardControllerUpdateCardAttributes', 'updateCardAttributesDto', updateCardAttributesDto)
            const localVarPath = `/card/{type}/{id}/attributes`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCardAttributesDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CardsCRUDApi - functional programming interface
 * @export
 */
export const CardsCRUDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CardsCRUDApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} type 
         * @param {CreateCardDto} createCardDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerCreate(type: string, createCardDto: CreateCardDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerCreate(type, createCardDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerFindAllInSpace(spaceID: string, type: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerFindAllInSpace(spaceID, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerFindAllInSpace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {string} parentID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerFindChildren(spaceID: string, type: string, parentID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerFindChildren(spaceID, type, parentID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerFindChildren']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerFindOne(spaceID: string, type: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerFindOne(spaceID, type, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} spaceID 
         * @param {string} type 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerRemove(spaceID: string, type: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerRemove(spaceID, type, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} type 
         * @param {string} id 
         * @param {UpdateCardDto} updateCardDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerUpdate(type: string, id: string, updateCardDto: UpdateCardDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerUpdate(type, id, updateCardDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} type 
         * @param {string} id 
         * @param {UpdateCardAttributesDto} updateCardAttributesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cardControllerUpdateCardAttributes(type: string, id: string, updateCardAttributesDto: UpdateCardAttributesDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cardControllerUpdateCardAttributes(type, id, updateCardAttributesDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardsCRUDApi.cardControllerUpdateCardAttributes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CardsCRUDApi - factory interface
 * @export
 */
export const CardsCRUDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CardsCRUDApiFp(configuration)
    return {
        /**
         * 
         * @param {CardsCRUDApiCardControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerCreate(requestParameters: CardsCRUDApiCardControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerCreate(requestParameters.type, requestParameters.createCardDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsCRUDApiCardControllerFindAllInSpaceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerFindAllInSpace(requestParameters: CardsCRUDApiCardControllerFindAllInSpaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerFindAllInSpace(requestParameters.spaceID, requestParameters.type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsCRUDApiCardControllerFindChildrenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerFindChildren(requestParameters: CardsCRUDApiCardControllerFindChildrenRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerFindChildren(requestParameters.spaceID, requestParameters.type, requestParameters.parentID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsCRUDApiCardControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerFindOne(requestParameters: CardsCRUDApiCardControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerFindOne(requestParameters.spaceID, requestParameters.type, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsCRUDApiCardControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerRemove(requestParameters: CardsCRUDApiCardControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerRemove(requestParameters.spaceID, requestParameters.type, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsCRUDApiCardControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerUpdate(requestParameters: CardsCRUDApiCardControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerUpdate(requestParameters.type, requestParameters.id, requestParameters.updateCardDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CardsCRUDApiCardControllerUpdateCardAttributesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cardControllerUpdateCardAttributes(requestParameters: CardsCRUDApiCardControllerUpdateCardAttributesRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cardControllerUpdateCardAttributes(requestParameters.type, requestParameters.id, requestParameters.updateCardAttributesDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cardControllerCreate operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerCreateRequest
 */
export interface CardsCRUDApiCardControllerCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerCreate
     */
    readonly type: string

    /**
     * 
     * @type {CreateCardDto}
     * @memberof CardsCRUDApiCardControllerCreate
     */
    readonly createCardDto: CreateCardDto
}

/**
 * Request parameters for cardControllerFindAllInSpace operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerFindAllInSpaceRequest
 */
export interface CardsCRUDApiCardControllerFindAllInSpaceRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindAllInSpace
     */
    readonly spaceID: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindAllInSpace
     */
    readonly type: string
}

/**
 * Request parameters for cardControllerFindChildren operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerFindChildrenRequest
 */
export interface CardsCRUDApiCardControllerFindChildrenRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindChildren
     */
    readonly spaceID: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindChildren
     */
    readonly type: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindChildren
     */
    readonly parentID: string
}

/**
 * Request parameters for cardControllerFindOne operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerFindOneRequest
 */
export interface CardsCRUDApiCardControllerFindOneRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindOne
     */
    readonly spaceID: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindOne
     */
    readonly type: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for cardControllerRemove operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerRemoveRequest
 */
export interface CardsCRUDApiCardControllerRemoveRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerRemove
     */
    readonly spaceID: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerRemove
     */
    readonly type: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for cardControllerUpdate operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerUpdateRequest
 */
export interface CardsCRUDApiCardControllerUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerUpdate
     */
    readonly type: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerUpdate
     */
    readonly id: string

    /**
     * 
     * @type {UpdateCardDto}
     * @memberof CardsCRUDApiCardControllerUpdate
     */
    readonly updateCardDto: UpdateCardDto
}

/**
 * Request parameters for cardControllerUpdateCardAttributes operation in CardsCRUDApi.
 * @export
 * @interface CardsCRUDApiCardControllerUpdateCardAttributesRequest
 */
export interface CardsCRUDApiCardControllerUpdateCardAttributesRequest {
    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerUpdateCardAttributes
     */
    readonly type: string

    /**
     * 
     * @type {string}
     * @memberof CardsCRUDApiCardControllerUpdateCardAttributes
     */
    readonly id: string

    /**
     * 
     * @type {UpdateCardAttributesDto}
     * @memberof CardsCRUDApiCardControllerUpdateCardAttributes
     */
    readonly updateCardAttributesDto: UpdateCardAttributesDto
}

/**
 * CardsCRUDApi - object-oriented interface
 * @export
 * @class CardsCRUDApi
 * @extends {BaseAPI}
 */
export class CardsCRUDApi extends BaseAPI {
    /**
     * 
     * @param {CardsCRUDApiCardControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerCreate(requestParameters: CardsCRUDApiCardControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerCreate(requestParameters.type, requestParameters.createCardDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsCRUDApiCardControllerFindAllInSpaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerFindAllInSpace(requestParameters: CardsCRUDApiCardControllerFindAllInSpaceRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerFindAllInSpace(requestParameters.spaceID, requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsCRUDApiCardControllerFindChildrenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerFindChildren(requestParameters: CardsCRUDApiCardControllerFindChildrenRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerFindChildren(requestParameters.spaceID, requestParameters.type, requestParameters.parentID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsCRUDApiCardControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerFindOne(requestParameters: CardsCRUDApiCardControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerFindOne(requestParameters.spaceID, requestParameters.type, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsCRUDApiCardControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerRemove(requestParameters: CardsCRUDApiCardControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerRemove(requestParameters.spaceID, requestParameters.type, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsCRUDApiCardControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerUpdate(requestParameters: CardsCRUDApiCardControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerUpdate(requestParameters.type, requestParameters.id, requestParameters.updateCardDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CardsCRUDApiCardControllerUpdateCardAttributesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardsCRUDApi
     */
    public cardControllerUpdateCardAttributes(requestParameters: CardsCRUDApiCardControllerUpdateCardAttributesRequest, options?: RawAxiosRequestConfig) {
        return CardsCRUDApiFp(this.configuration).cardControllerUpdateCardAttributes(requestParameters.type, requestParameters.id, requestParameters.updateCardAttributesDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SpaceCRUDApi - axios parameter creator
 * @export
 */
export const SpaceCRUDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateSpaceDto} createSpaceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerCreate: async (createSpaceDto: CreateSpaceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSpaceDto' is not null or undefined
            assertParamExists('spaceControllerCreate', 'createSpaceDto', createSpaceDto)
            const localVarPath = `/space`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSpaceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/space`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('spaceControllerFindOne', 'id', id)
            const localVarPath = `/space/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('spaceControllerRemove', 'id', id)
            const localVarPath = `/space/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpaceDto} updateSpaceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerUpdate: async (id: string, updateSpaceDto: UpdateSpaceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('spaceControllerUpdate', 'id', id)
            // verify required parameter 'updateSpaceDto' is not null or undefined
            assertParamExists('spaceControllerUpdate', 'updateSpaceDto', updateSpaceDto)
            const localVarPath = `/space/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSpaceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpaceCRUDApi - functional programming interface
 * @export
 */
export const SpaceCRUDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpaceCRUDApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateSpaceDto} createSpaceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async spaceControllerCreate(createSpaceDto: CreateSpaceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.spaceControllerCreate(createSpaceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpaceCRUDApi.spaceControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async spaceControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.spaceControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpaceCRUDApi.spaceControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async spaceControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.spaceControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpaceCRUDApi.spaceControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async spaceControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.spaceControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpaceCRUDApi.spaceControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpaceDto} updateSpaceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async spaceControllerUpdate(id: string, updateSpaceDto: UpdateSpaceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.spaceControllerUpdate(id, updateSpaceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpaceCRUDApi.spaceControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SpaceCRUDApi - factory interface
 * @export
 */
export const SpaceCRUDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpaceCRUDApiFp(configuration)
    return {
        /**
         * 
         * @param {SpaceCRUDApiSpaceControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerCreate(requestParameters: SpaceCRUDApiSpaceControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.spaceControllerCreate(requestParameters.createSpaceDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.spaceControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SpaceCRUDApiSpaceControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerFindOne(requestParameters: SpaceCRUDApiSpaceControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.spaceControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SpaceCRUDApiSpaceControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerRemove(requestParameters: SpaceCRUDApiSpaceControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.spaceControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SpaceCRUDApiSpaceControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spaceControllerUpdate(requestParameters: SpaceCRUDApiSpaceControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.spaceControllerUpdate(requestParameters.id, requestParameters.updateSpaceDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for spaceControllerCreate operation in SpaceCRUDApi.
 * @export
 * @interface SpaceCRUDApiSpaceControllerCreateRequest
 */
export interface SpaceCRUDApiSpaceControllerCreateRequest {
    /**
     * 
     * @type {CreateSpaceDto}
     * @memberof SpaceCRUDApiSpaceControllerCreate
     */
    readonly createSpaceDto: CreateSpaceDto
}

/**
 * Request parameters for spaceControllerFindOne operation in SpaceCRUDApi.
 * @export
 * @interface SpaceCRUDApiSpaceControllerFindOneRequest
 */
export interface SpaceCRUDApiSpaceControllerFindOneRequest {
    /**
     * 
     * @type {string}
     * @memberof SpaceCRUDApiSpaceControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for spaceControllerRemove operation in SpaceCRUDApi.
 * @export
 * @interface SpaceCRUDApiSpaceControllerRemoveRequest
 */
export interface SpaceCRUDApiSpaceControllerRemoveRequest {
    /**
     * 
     * @type {string}
     * @memberof SpaceCRUDApiSpaceControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for spaceControllerUpdate operation in SpaceCRUDApi.
 * @export
 * @interface SpaceCRUDApiSpaceControllerUpdateRequest
 */
export interface SpaceCRUDApiSpaceControllerUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof SpaceCRUDApiSpaceControllerUpdate
     */
    readonly id: string

    /**
     * 
     * @type {UpdateSpaceDto}
     * @memberof SpaceCRUDApiSpaceControllerUpdate
     */
    readonly updateSpaceDto: UpdateSpaceDto
}

/**
 * SpaceCRUDApi - object-oriented interface
 * @export
 * @class SpaceCRUDApi
 * @extends {BaseAPI}
 */
export class SpaceCRUDApi extends BaseAPI {
    /**
     * 
     * @param {SpaceCRUDApiSpaceControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceCRUDApi
     */
    public spaceControllerCreate(requestParameters: SpaceCRUDApiSpaceControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return SpaceCRUDApiFp(this.configuration).spaceControllerCreate(requestParameters.createSpaceDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceCRUDApi
     */
    public spaceControllerFindAll(options?: RawAxiosRequestConfig) {
        return SpaceCRUDApiFp(this.configuration).spaceControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SpaceCRUDApiSpaceControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceCRUDApi
     */
    public spaceControllerFindOne(requestParameters: SpaceCRUDApiSpaceControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return SpaceCRUDApiFp(this.configuration).spaceControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SpaceCRUDApiSpaceControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceCRUDApi
     */
    public spaceControllerRemove(requestParameters: SpaceCRUDApiSpaceControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return SpaceCRUDApiFp(this.configuration).spaceControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SpaceCRUDApiSpaceControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceCRUDApi
     */
    public spaceControllerUpdate(requestParameters: SpaceCRUDApiSpaceControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return SpaceCRUDApiFp(this.configuration).spaceControllerUpdate(requestParameters.id, requestParameters.updateSpaceDto, options).then((request) => request(this.axios, this.basePath));
    }
}



