name: Self-update on cards-webserver-nestjs-updated
on:
  repository_dispatch:
    types: [cards-webserver-nestjs-updated]
  workflow_dispatch: # This line enables manual triggering
jobs:
  generate-client-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: anton-107/cards-webserver-client-ts-axios
          ref: main

      - name: Configure Git
        run: |
          git config --global user.email "bot-107@github.com"
          git config --global user.name "Bot 107"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      #- run: npm install
      #- run: npm update
      #- run: npm run generate-source
      #- run: npm run build
      - run: date > timestamp.txt
      - run: git add . && git commit -m 'auto-build'
      - name: Push changes
        run: git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
            GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
