name: Self-update on cards-webserver-nestjs-updated
on:
  repository_dispatch:
    types: [cards-webserver-nestjs-updated]
jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm update
      - run: npm run generate-source
      - run: npm run build
      - run: git add . && git commit -m 'auto-build'
      - name: Push changes
        run: git push origin main
